/*
 * @(#)IGenericSensorProxy.java 
 */

package javaBot.sensors.ws.proxyImpls;

//**********************************************************
//<autogenerated>
//	This code was auto-generated by wsdlgen, Version 0.1
//	Changes to this file may cause incorrect behavior and will be lost if
//	the code is regenerated
//
//	This class is a mirror interface proxy class to a WebService Interface.
//	When this proxy class is instantiated with the Internet Address a muvium
//	device programmed with the matching WebService this proxy class will
//	transparently invoke the remote method on the muvium device.
//
//	<usage>
//	IGenericSensor proxy = new IGenericSensorProxy("10.1.1.7");
//	proxy.method();
//	</usage>
//</autogenerated>
//**********************************************************

import javaBot.sensors.ws.interfaces.ISensorSim;

import com.muvium.web.services.protocols.HttpGetClientProtocol;

public class ISensorSimProxy extends HttpGetClientProtocol implements ISensorSim
{
	String	myIPAddress;

	public ISensorSimProxy(String ipAddress)
	{
		myIPAddress = ipAddress;
	}

	public String getSensorValue(int int0)
	{
		return invokeString(myIPAddress, "//getSensorValue", new Object[] {new Integer(int0)});
	}

	public String getName(String name)
	{
		return invokeString(myIPAddress, "//getName", new Object[] {name});
	}

}
